exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- bash -c 'omarchy-toggle-enabled waybar-off || exec waybar'
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = omarchy-first-run
exec-once = omarchy-powerprofiles-init
exec-once = uwsm-app -- omarchy-hyprland-monitor-watch

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

# Run post-boot hooks after startup config has loaded
exec-once = sleep 2 && omarchy-hook post-boot

# Always send Steam to workspace 3
windowrule = match:class ^(steam)$, workspace 3

# Auto-start Steam on login in workspace 3
exec-once = [workspace 3 silent] steam -silent
windowrule = focus_on_activate off, match:class ^(steam)$
windowrule = no_initial_focus on, match:class ^(steam)$
windowrule = stay_focused on, match:class ^steam$, match:title ^Friends List$

# Open Discord on login silently
# windowrule = match:class ^(discord)$, workspace 4  # Couldn't get it to work properly off launch
exec-once = discord --start-minimized
