accent = "#ca2cb0"
cursor = "#f5eafd"
foreground = "#f5eafd"
background = "#0a0716"
selection_foreground = "#0a0716"
selection_background = "#f5eafd"

color0 = "#0a0716"
color1 = "#a70b68"
color2 = "#7f049e"
color3 = "#790aac"
color4 = "#ca2cb0"
color5 = "#a604e9"
color6 = "#c429b2"
color7 = "#c78bf5"
color8 = "#8c53b7"
color9 = "#f1279f"
color10 = "#c911f8"
color11 = "#b52af3"
color12 = "#e37bd1"
color13 = "#cc58fc"
color14 = "#ef6469"
color15 = "#f5eafd"
